<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.kpro</groupId>
  <artifactId>common</artifactId>
  <!--	<version>0.0.2-SNAPSHOT</version>-->
  <version>0.0.3-SNAPSHOT</version>
  <name>common</name>
  <description>Demo project for Spring Boot</description>

  <properties>
    <java.version>21</java.version>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <!--		<spring.boot.version>3.1.5</spring.boot.version>-->
    <!--		<spring-cloud.version>2022.0.5</spring-cloud.version>-->

    <spring.boot.version>3.5.9</spring.boot.version>
    <spring-cloud.version>2025.0.1</spring-cloud.version>
  </properties>

  <distributionManagement>
    <repository>
      <id>nexus</id>
      <url>http://localhost:8081/repository/maven-releases/</url>
    </repository>

    <snapshotRepository>
      <id>nexus</id>
      <url>http://localhost:8081/repository/maven-snapshots/</url>
    </snapshotRepository>
  </distributionManagement>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring.boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.httpcomponents.client5</groupId>
      <artifactId>httpclient5</artifactId>
    </dependency>

    <!--    https://docs.spring.io/spring-cloud-config/docs/current/reference/html-->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-config</artifactId>
    </dependency>

    <!--		https://docs.spring.io/spring-cloud-kubernetes/reference/getting-started.html-->
    <!--    You CANNOT combine starters from Fabric8 and Kubernetes Java Clients.
    You must pick one library to use and use the starters for that library only.-->

    <!--		Discovery Client implementation that resolves service names to Kubernetes Services.-->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-kubernetes-client</artifactId>
    </dependency>

    <!--		Load application properties from Kubernetes ConfigMaps and Secrets.
    Reload application properties when a ConfigMap or Secret changes.-->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-kubernetes-client-config</artifactId>
    </dependency>

    <!--    There are two "modes" in which load balancer works: POD and SERVICE,
    denoted by the property (default being POD)-->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-kubernetes-client-loadbalancer</artifactId>
    </dependency>

    <!--		<dependency>-->
    <!--			<groupId>org.springframework.cloud</groupId>-->
    <!--			<artifactId>spring-cloud-starter-openfeign</artifactId>-->
    <!--		</dependency>-->
    <!--		<dependency>-->
    <!--			<groupId>io.github.openfeign</groupId>-->
    <!--			<artifactId>feign-httpclient</artifactId>-->
    <!--			<version>12.3</version>-->
    <!--		</dependency>-->

    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
      <optional>true</optional>
    </dependency>

    <dependency>
      <groupId>com.nimbusds</groupId>
      <artifactId>nimbus-jose-jwt</artifactId>
      <version>9.10</version>
    </dependency>

    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-s3</artifactId>
      <version>1.12.348</version>
    </dependency>

    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.11.0</version>
    </dependency>
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.14.0</version>
        <configuration>
          <source>${maven.compiler.source}</source>
          <target>${maven.compiler.target}</target>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
